test

diff --git a/.github/workflows/release_test.yml b/.github/workflows/release_test.yml
--- a/.github/workflows/release_test.yml
+++ b/.github/workflows/release_test.yml
@@ -35,8 +35,8 @@ jobs:
           # Check if version number is newer than the latest tag (strip 'v' from tag)
           LATEST_TAG=$(git tag --list 'v*' | tail -1 | sed 's/v//')
           if [[ $VERSION < $LATEST_TAG ]]; then
-              echo "Version number is older than the latest tag"
-              exit 1
+            echo "Version number is older than the latest tag"
+            exit 1
           fi
           echo "VERSION=$VERSION" >> $GITHUB_ENV
         shell: bash
@@ -47,29 +47,31 @@ jobs:
         run: |
           # Assert that the release branch is not master (we merge to master from release branches)
           if [[ $GITHUB_REF == refs/heads/master ]]; then
-              echo "Cannot release from master branch"
-              exit 1
+            echo "Cannot release from master branch"
+            exit 1
           fi
           # Fetch history from the remote
           git fetch --unshallow
           # Assert that master is an ancestor of the release branch
           if ! git merge-base --is-ancestor origin/master $GITHUB_REF; then
-              echo "Release branch is not a parent of master"
-              exit 1
+            echo "Release branch is not a parent of master"
+            exit 1
           fi
           # If the release branch is not dev, create a new local branch from origin/dev and check that
           # it can be fast-forward rebased onto $GITHUB_REF
+          IS_DEV=0
           if [[ $GITHUB_REF != refs/heads/dev ]]; then
-              git checkout -b dev origin/dev
-              if ! git rebase --onto $GITHUB_REF dev; then
-                  echo "Cannot rebase dev onto $GITHUB_REF. Please rebase dev onto $GITHUB_REF and push the changes"
-                  exit 1
-              fi
-              # Return to the original branch
-              git checkout -
-              git branch -D dev
+            IS_DEV=1
+            git checkout -b dev origin/dev
+            if ! git rebase --onto $GITHUB_REF dev; then
+              echo "Cannot rebase dev onto $GITHUB_REF. Please rebase dev onto $GITHUB_REF and push the changes"
+              exit 1
+            fi
+            # Return to the original branch
+            git checkout -
+            git branch -D dev
           fi
-          echo "IS_DEV=$([[ $GITHUB_REF == refs/heads/dev ]])" >> $GITHUB_ENV
+          echo "IS_DEV=$IS_DEV" >> $GITHUB_ENV
           echo $VERSION $IS_DEV
         shell: bash
   SlackNotification:
