test

diff --git a/.github/workflows/release_test.yml b/.github/workflows/release_test.yml
--- a/.github/workflows/release_test.yml
+++ b/.github/workflows/release_test.yml
@@ -45,27 +45,26 @@ jobs:
       - name: Check release branch status
         id: check_branch
         run: |
-          echo "VERSION=$VERSION"
-          # # Assert that the release branch is not master (we merge to master from release branches)
-          # if [[ $GITHUB_REF == refs/heads/master ]]; then
-          #     echo "Cannot release from master branch"
-          #     exit 1
-          # fi
-          # # Assert that master is an ancestor of the release branch
-          # if ! git merge-base --is-ancestor master $GITHUB_REF; then
-          #     echo "Release branch is not a parent of master"
-          #     exit 1
-          # fi
-          # # If the release branch is not dev, create a new local branch from origin/dev and check that
-          # # it can be fast-forward rebased onto $GITHUB_REF
-          # if [[ $GITHUB_REF != refs/heads/dev ]]; then
-          #     git checkout -b dev origin/dev
-          #     if ! git rebase --onto $GITHUB_REF dev; then
-          #         echo "Cannot rebase dev onto $GITHUB_REF. Please rebase dev onto $GITHUB_REF and push the changes"
-          #         exit 1
-          #     fi
-          #     # Return to the original branch
-          #     git checkout -
-          #     git branch -D dev
-          # fi
+          # Assert that the release branch is not master (we merge to master from release branches)
+          if [[ $GITHUB_REF == refs/heads/master ]]; then
+              echo "Cannot release from master branch"
+              exit 1
+          fi
+          # Assert that master is an ancestor of the release branch
+          if ! git merge-base --is-ancestor master $GITHUB_REF; then
+              echo "Release branch is not a parent of master"
+              exit 1
+          fi
+          # If the release branch is not dev, create a new local branch from origin/dev and check that
+          # it can be fast-forward rebased onto $GITHUB_REF
+          if [[ $GITHUB_REF != refs/heads/dev ]]; then
+              git checkout -b dev origin/dev
+              if ! git rebase --onto $GITHUB_REF dev; then
+                  echo "Cannot rebase dev onto $GITHUB_REF. Please rebase dev onto $GITHUB_REF and push the changes"
+                  exit 1
+              fi
+              # Return to the original branch
+              git checkout -
+              git branch -D dev
+          fi
         shell: bash
